#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Ente kaldırma işlemi başlatılıyor..."

# Docker konteynerlerini durdur ve kaldır
docker compose -f /opt/ente/compose.yaml down || true

# Kurulum dizinini sil
rm -rf /opt/ente

ynh_script_progression --message="Ente başarıyla kaldırıldı!"
